name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.environment == 'staging'
    environment: staging

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to staging
      run: |
        python scripts/deploy.py \
          --project-id ${{ secrets.GCP_PROJECT_ID }} \
          --environment staging \
          --version ${{ github.sha }}
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ secrets.GCP_REGION }}

    - name: Run smoke tests
      run: |
        python scripts/smoke_test.py \
          --project-id ${{ secrets.GCP_PROJECT_ID }} \
          --environment staging

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up GCP credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to production
      run: |
        python scripts/deploy.py \
          --project-id ${{ secrets.GCP_PROJECT_ID }} \
          --environment production \
          --version ${{ github.sha }}
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ secrets.GCP_REGION }}

    - name: Run smoke tests
      run: |
        python scripts/smoke_test.py \
          --project-id ${{ secrets.GCP_PROJECT_ID }} \
          --environment production

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Release of version v${{ github.run_number }}
          Commit: ${{ github.sha }}
        draft: false
        prerelease: false
